<?php
/**
 * 重写handle中render渲染方法
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/5/8 0008
 * Time: 22:45
 */
namespace app\common\exception;
use Exception;
use think\exception\Handle;
use think\facade\Config;

class ApiHandleException extends Handle
{
    /**
     * 重写该方法  错误输出兼容api输出方式
     * @param Exception $e
     * @return \think\Response
     */
    public function render(Exception $e)
    {
        if(Config::get('app.app_debug') == true){
            return parent::render($e); // TODO: Change the autogenerated stub
        }
        return apiShow('0', $e->getMessage(), '', $e->HttpCode);
    }
}
